apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seafile-tailscale
  namespace: seafile
  annotations:
    # Use this if you want to force HTTPS redirect through the Tailscale ingress
    # tailscale.com/hostname: seafile
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - seafile # This requests the certificate for 'seafile' on your tailnet
  rules:
  - host: seafile # Access via https://seafile.<your-tailnet-domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: seafile
            port:
              number: 80
