apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-nextcloud-ingress
  namespace: nextcloud
  annotations:
    tailscale.com/http-redirect: "true"
spec:
  defaultBackend:
    service:
      name: nextcloud
      port:
        number: 8080
  ingressClassName: tailscale

