apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mikrotik-ingress
  namespace: tailscale
  annotations:
    # Define o nome que aparecer√° no seu painel Tailscale
    tailscale.com/hostname: "mikrotik-homelab"
spec:
  ingressClassName: tailscale
  rules:
  -  http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mikrotik-tailscale
            port:
              number: 80
